### ISSUE TITLE
Add support for math equations in the essay sections

### ISSUE THREAD

**Issue by sergey-negrashov** [techfolios/techfolios.github.io#1]
It would be really helpful if the essay section supported tex-like math equations. Something along the lines of MathJax.

**Comment by philipmjohnson** [comment]
Now supported in the head (both master and gh-pages branches).

* Update your own techfolio by merging from upstream (http://techfolios.github.io/userguide.html#2.Gettingupdates)

* Set mathjax: true in your _config.yml

* Use MathJax. Here's a quick start from the Morea User Guide:
http://morea-framework.github.io/userguide.html#Equationsupport

LMK if you run into problems by re-opening this issue.
