### ISSUE TITLE
Update Initialization Page

### ISSUE THREAD

**Issue by mdrxy** [techfolios/techfolios.github.io#2]
[https://techfolios.github.io/docs/quick-start/initialization#set-workflow-permissions-to-read-and-write](https://techfolios.github.io/docs/quick-start/initialization#set-workflow-permissions-to-read-and-write)

After the sentence `Check that Workflow permissions is set to "Read and write permissions".` you should consider adding the sentence `Check the box for "Allow GitHub Actions to create and approve pull requests"` since this isn't enabled by default as of the time of this writing.

Furthermore, after the sentence `Also, please note that the very first time you try to build your portfolio, it takes about five minutes, which is a long time!` it may be worth noting that `Visiting your website will display the following text for a few minutes while the page is built:`

`--- title: Home layout: home --- {% include about/about.html %} {% include projects/projects.html limit=4 %} {% include essays/essays.html limit=6 %}`

I open this issue in response to my own confusion during the setup process and hope that these changes will help others!

**Comment by philipmjohnson** [comment]
Thanks, I've added your updates!
