### ISSUE TITLE
Remove Hack My Resume URL

### ISSUE THREAD

**Issue by mdrxy** [techfolios/techfolios.github.io#3]
[https://techfolios.github.io/docs/user-guide/anatomy-of-bio-json](https://techfolios.github.io/docs/user-guide/anatomy-of-bio-json)

Dead link within `If you want to transmogrify your bio.json file into other formats, see [Hack My Resume](http://please.hackmyresume.com/).`

**Comment by philipmjohnson** [comment]
Removed, thanks!
